In [ ]:
# --- Setup and Installations ---
!pip install --upgrade yfinance yahoofinancials requests urllib3

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Collecting yfinance
  Downloading yfinance-1.2.1-py2.py3-none-any.whl.metadata (6.1 kB)
Collecting yahoofinancials
  Downloading yahoofinancials-1.20.tar.gz (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.9/51.9 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (2.5.0)
Collecting urllib3
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (18 kB)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Collecting appdirs>=1.4.4 (from yahoofinancials)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from yahoofinancials) (6.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Downloading yfinance-1.2.1-py2.py3-none-any.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 7.7 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 5.4 MB/s eta 0:00:00
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 11.6 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 65.5 MB/s eta 0:00:00
Building wheels for collected packages: yahoofinancials
  Building wheel for yahoofinancials (setup.py) ... done
  Created wheel for yahoofinancials: filename=yahoofinancials-1.20-py3-none-any.whl size=38618 sha256=5d37e9fb5b43b07b9a96ef766e1dc4f217272b8ddef777e7a272b5b28295df08
  Stored in directory: /root/.cache/pip/wheels/b0/e1/ca/e683b02e57db550881c8ebb89ba3eccb7a5c0ebfad7f03acea
Successfully built yahoofinancials
Installing collected packages: appdirs, urllib3, requests, yahoofinancials, curl_cffi, yfinance
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: curl_cffi
    Found existing installation: curl_cffi 0.14.0
    Uninstalling curl_cffi-0.14.0:
      Successfully uninstalled curl_cffi-0.14.0
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.66
    Uninstalling yfinance-0.2.66:
      Successfully uninstalled yfinance-0.2.66
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.1 which is incompatible.
Successfully installed appdirs-1.4.4 curl_cffi-0.15.0 requests-2.33.1 urllib3-2.6.3 yahoofinancials-1.20 yfinance-1.2.1

In [ ]:
# --- Imports ---
import pandas as pd
import yfinance as yf
from yahoofinancials import YahooFinancials
import requests
from io import StringIO
from IPython.display import display
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go

In [ ]:
# TASK 1: Extract and store the S&P 500 Tickers
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
response.raise_for_status()

# Read all tables on the page
tables = pd.read_html(StringIO(response.text))

# Find the table that contains a 'Symbol' column
sp500_table = None
for table in tables:
    cols_lower = [str(c).lower() for c in table.columns]
    if "symbol" in cols_lower:
        sp500_table = table.copy()
        break

if sp500_table is None:
    raise ValueError("No table with a 'Symbol' column found on the page.")

# Standardise column name to 'Symbol'
for col in sp500_table.columns:
    if str(col).lower() == "symbol":
        symbol_col = col
        break

sp500_table.rename(columns={symbol_col: "Symbol"}, inplace=True)

# Clean tickers (BRK.B → BRK-B) for Yahoo Finance
sp500_table["Symbol"] = (
    sp500_table["Symbol"]
    .astype(str)
    .str.replace(".", "-", regex=False)
)

In [ ]:
# FINAL LIST OF TICKERS
tickers = sp500_table["Symbol"].unique().tolist()
print("Task 1 Complete: Number of tickers extracted:", len(tickers))

#Relevant code and extracted list of tickers
print("Extracted Tickers List:", tickers)

Task 1 Complete: Number of tickers extracted: 503
Extracted Tickers List: ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'AON', 'APA', 'APO', 'AAPL', 'AMAT', 'APP', 'APTV', 'ACGL', 'ADM', 'ARES', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BAX', 'BDX', 'BRK-B', 'BBY', 'TECH', 'BIIB', 'BLK', 'BX', 'XYZ', 'BK', 'BA', 'BKNG', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF-B', 'BLDR', 'BG', 'BXP', 'CHRW', 'CDNS', 'CPT', 'CPB', 'COF', 'CAH', 'CCL', 'CARR', 'CVNA', 'CASY', 'CAT', 'CBOE', 'CBRE', 'CDW', 'COR', 'CNC', 'CNP', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CIEN', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'COHR', 'COIN', 'CL', 'CMCSA', 'FIX', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CPAY', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CRH', 'CRWD', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DDOG', 'DVA', 'DECK', 'DE', 'DELL', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR', 'DG', 'DLTR', 'D', 'DPZ', 'DASH', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'ETN', 'EBAY', 'SATS', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'EME', 'EMR', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ERIE', 'ESS', 'EL', 'EG', 'EVRG', 'ES', 'EXC', 'EXE', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FISV', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GE', 'GEHC', 'GEV', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GDDY', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'DOC', 'HSIC', 'HSY', 'HPE', 'HLT', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'PODD', 'INTC', 'IBKR', 'ICE', 'IFF', 'IP', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KKR', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LVS', 'LDOS', 'LEN', 'LII', 'LLY', 'LIN', 'LYV', 'LMT', 'L', 'LOW', 'LULU', 'LITE', 'LYB', 'MTB', 'MPC', 'MAR', 'MRSH', 'MLM', 'MAS', 'MA', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PLTR', 'PANW', 'PSKY', 'PH', 'PAYX', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'PWR', 'QCOM', 'DGX', 'Q', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'HOOD', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SNDK', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SW', 'SNA', 'SOLV', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TER', 'TSLA', 'TXN', 'TPL', 'TXT', 'TMO', 'TJX', 'TKO', 'TTD', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VRT', 'VTRS', 'VICI', 'V', 'VST', 'VMC', 'WRB', 'GWW', 'WAB', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WY', 'WSM', 'WMB', 'WTW', 'WDAY', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS']

In [42]:
# TASK 2: Load S&P 500 Tickers daily market performance (01-01-2022 to 01-01-2025)
start_date = "2022-01-01"
end_date = "2025-01-01"

print("\nTask 2: Downloading raw historical data (All Metrics)...")
# Gets Adj Close
market_data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=False)

# Provide the extracted data size and dimensionality
print(f"Task 2 Complete: Raw Data Shape: {market_data.shape}")
print(f"Total elements in landing zone: {market_data.size}")
display(market_data.head())

[                       0%                       ]

Task 2: Downloading raw historical data (All Metrics)...

[*********             18%                       ]  91 of 503 completedERROR:yfinance:$Q: possibly delisted; no price data found  (1d 2022-01-01 -> 2025-01-01) (Yahoo error = "Data doesn't exist for startDate = 1641013200, endDate = 1735707600")
[**********************99%***********************]  496 of 503 completedERROR:yfinance:$SNDK: possibly delisted; no price data found  (1d 2022-01-01 -> 2025-01-01) (Yahoo error = "Data doesn't exist for startDate = 1641013200, endDate = 1735707600")
[*********************100%***********************]  503 of 503 completed
ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['Q', 'SNDK']: possibly delisted; no price data found  (1d 2022-01-01 -> 2025-01-01) (Yahoo error = "Data doesn't exist for startDate = 1641013200, endDate = 1735707600")

Task 2 Complete: Raw Data Shape: (753, 3018)
Total elements in landing zone: 2272554

Price        Adj Close                                                  \
Ticker               A        AAPL        ABBV        ABNB         ABT
Date
2022-01-03  151.702133  178.103653  115.847198  172.679993  128.345978
2022-01-04  146.573669  175.843277  115.624802  170.800003  125.327492
2022-01-05  144.062759  171.165863  116.232162  162.250000  124.764435
2022-01-06  144.566864  168.308517  115.684677  159.750000  124.745956
2022-01-07  140.718094  168.474869  115.385269  166.050003  125.133629

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2022-01-03  42.362530  380.485321  564.369995  164.526489  60.037258  ...
2022-01-04  42.914051  377.766266  554.000000  163.040497  61.151531  ...
2022-01-05  42.410072  371.113617  514.429993  160.523590  60.673988  ...
2022-01-06  42.657307  353.192322  514.119995  161.034409  61.213440  ...
2022-01-07  42.856995  346.418152  510.700012  156.808624  61.735180  ...

Price        Volume                                                          \
Ticker           WY     WYNN      XEL       XOM      XYL       XYZ      YUM
Date
2022-01-03  3831100  2437800  3501100  24282400   759100   7315700  1251400
2022-01-04  3089700  2292300  4197000  38584000   925400  14768500   935900
2022-01-05  3737600  3439900  4166000  34033300  1090200  17546200   977900
2022-01-06  3315200  2583200  2296000  30668500   703400  16244200   862400
2022-01-07  3309900  1720400  2673100  23985400   765000   9426000   833700

Price
Ticker          ZBH    ZBRA      ZTS
Date
2022-01-03  1184809  272600  2772700
2022-01-04  1400800  346000  4664000
2022-01-05  1895715  403700  4749400
2022-01-06  1088813  338300  3103400
2022-01-07  1690230  432800  2206500

[5 rows x 3018 columns]

In [32]:
market_data

Price        Adj Close                                                  \
Ticker               A        AAPL        ABBV        ABNB         ABT
Date
2022-01-03  151.702133  178.103653  115.847221  172.679993  128.345978
2022-01-04  146.573669  175.843216  115.624817  170.800003  125.327538
2022-01-05  144.062744  171.165817  116.232185  162.250000  124.764435
2022-01-06  144.566864  168.308502  115.684677  159.750000  124.745941
2022-01-07  140.718094  168.474823  115.385269  166.050003  125.133652
...                ...         ...         ...         ...         ...
2024-12-24  134.457260  256.797211  172.530670  134.990005  112.058296
2024-12-26  134.190506  257.612701  171.763855  135.320007  112.556282
2024-12-27  133.904007  254.201370  170.623230  133.384995  112.282883
2024-12-30  132.797531  250.829788  168.888351  131.809998  110.144440
2024-12-31  132.963806  249.059464  170.326126  131.410004  110.447144

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2022-01-03  42.362530  380.485260  564.369995  164.526474  60.037266  ...
2022-01-04  42.914051  377.766235  554.000000  163.040482  61.151535  ...
2022-01-05  42.410072  371.113556  514.429993  160.523590  60.673992  ...
2022-01-06  42.657307  353.192322  514.119995  161.034439  61.213421  ...
2022-01-07  42.856995  346.418091  510.700012  156.808624  61.735180  ...
...               ...         ...         ...         ...        ...  ...
2024-12-24  92.669998  353.541504  447.940002  213.882050  48.364082  ...
2024-12-26  92.930000  352.368317  450.160004  213.852646  48.344975  ...
2024-12-27  92.339996  348.213348  446.480011  212.803284  48.316322  ...
2024-12-30  91.889999  344.605896  445.799988  208.458771  47.829144  ...
2024-12-31  92.349998  343.921570  444.679993  208.360718  48.259003  ...

Price        Volume                                                          \
Ticker           WY     WYNN      XEL       XOM      XYL       XYZ      YUM
Date
2022-01-03  3831100  2437800  3501100  24282400   759100   7315700  1251400
2022-01-04  3089700  2292300  4197000  38584000   925400  14768500   935900
2022-01-05  3737600  3439900  4166000  34033300  1090200  17546200   977900
2022-01-06  3315200  2583200  2296000  30668500   703400  16244200   862400
2022-01-07  3309900  1720400  2673100  23985400   765000   9426000   833700
...             ...      ...      ...       ...      ...       ...      ...
2024-12-24  1780100   692800   943900   7807000   379300   2197700   533000
2024-12-26  1736500  1218900  1394900   9652400   575700   2991100  1040900
2024-12-27  2320500  1086700  2015000  11943900   552400   4140800  1146300
2024-12-30  2914700  2180100  2642900  11080800   586800   5383800  1144600
2024-12-31  3125200  1612600  2143800  12387800   641600   4989400  1217100

Price
Ticker          ZBH    ZBRA      ZTS
Date
2022-01-03  1184809  272600  2772700
2022-01-04  1400800  346000  4664000
2022-01-05  1895715  403700  4749400
2022-01-06  1088813  338300  3103400
2022-01-07  1690230  432800  2206500
...             ...     ...      ...
2024-12-24   458600   88700  1023600
2024-12-26  1277300  140100  2167200
2024-12-27   743400  287200  1800100
2024-12-30  1532000  211300  1531400
2024-12-31   683300  327900  1327400

[753 rows x 3018 columns]

In [39]:
# TASK 3: Identify and remove invalid data

# 1. Identify tickers with ANY missing data in the 'Close' column
# We slice into 'Close' to find the specific ticker names with NaNs
missing_data_mask = market_data['Close'].isnull().any()
tickers_to_remove = missing_data_mask[missing_data_mask].index.tolist()

print(f"Tickers identified for removal: {len(tickers_to_remove)}")

# 2. Remove these tickers from the entire warehouse (Level 1)
clean_data = market_data.drop(labels=tickers_to_remove, axis=1, level=1)

# 3. Final alignment: Drop dates if the entire market was closed (holidays)
clean_data = clean_data.dropna(axis=0, how='all')

print("-" * 30)
print(f"Task 3 Complete: Full ETL Cleanup")
print(f"Cleaned Dimensionality (Rows, Columns): {clean_data.shape}")
print(f"Total Surviving Tickers: {clean_data.shape[1] // 5}") # Based on 5 attributes
print("-" * 30)

Tickers identified for removal: 8
------------------------------
Task 3 Complete: Full ETL Cleanup
Cleaned Dimensionality (Rows, Columns): (753, 2970)
Total Surviving Tickers: 594
------------------------------

In [40]:
clean_data

Price        Adj Close                                                  \
Ticker               A        AAPL        ABBV        ABNB         ABT
Date
2022-01-03  151.702133  178.103653  115.847221  172.679993  128.345978
2022-01-04  146.573669  175.843216  115.624817  170.800003  125.327538
2022-01-05  144.062744  171.165817  116.232185  162.250000  124.764435
2022-01-06  144.566864  168.308502  115.684677  159.750000  124.745941
2022-01-07  140.718094  168.474823  115.385269  166.050003  125.133652
...                ...         ...         ...         ...         ...
2024-12-24  134.457260  256.797211  172.530670  134.990005  112.058296
2024-12-26  134.190506  257.612701  171.763855  135.320007  112.556282
2024-12-27  133.904007  254.201370  170.623230  133.384995  112.282883
2024-12-30  132.797531  250.829788  168.888351  131.809998  110.144440
2024-12-31  132.963806  249.059464  170.326126  131.410004  110.447144

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2022-01-03  42.362530  380.485260  564.369995  164.526474  60.037266  ...
2022-01-04  42.914051  377.766235  554.000000  163.040482  61.151535  ...
2022-01-05  42.410072  371.113556  514.429993  160.523590  60.673992  ...
2022-01-06  42.657307  353.192322  514.119995  161.034439  61.213421  ...
2022-01-07  42.856995  346.418091  510.700012  156.808624  61.735180  ...
...               ...         ...         ...         ...        ...  ...
2024-12-24  92.669998  353.541504  447.940002  213.882050  48.364082  ...
2024-12-26  92.930000  352.368317  450.160004  213.852646  48.344975  ...
2024-12-27  92.339996  348.213348  446.480011  212.803284  48.316322  ...
2024-12-30  91.889999  344.605896  445.799988  208.458771  47.829144  ...
2024-12-31  92.349998  343.921570  444.679993  208.360718  48.259003  ...

Price        Volume                                                          \
Ticker           WY     WYNN      XEL       XOM      XYL       XYZ      YUM
Date
2022-01-03  3831100  2437800  3501100  24282400   759100   7315700  1251400
2022-01-04  3089700  2292300  4197000  38584000   925400  14768500   935900
2022-01-05  3737600  3439900  4166000  34033300  1090200  17546200   977900
2022-01-06  3315200  2583200  2296000  30668500   703400  16244200   862400
2022-01-07  3309900  1720400  2673100  23985400   765000   9426000   833700
...             ...      ...      ...       ...      ...       ...      ...
2024-12-24  1780100   692800   943900   7807000   379300   2197700   533000
2024-12-26  1736500  1218900  1394900   9652400   575700   2991100  1040900
2024-12-27  2320500  1086700  2015000  11943900   552400   4140800  1146300
2024-12-30  2914700  2180100  2642900  11080800   586800   5383800  1144600
2024-12-31  3125200  1612600  2143800  12387800   641600   4989400  1217100

Price
Ticker          ZBH    ZBRA      ZTS
Date
2022-01-03  1184809  272600  2772700
2022-01-04  1400800  346000  4664000
2022-01-05  1895715  403700  4749400
2022-01-06  1088813  338300  3103400
2022-01-07  1690230  432800  2206500
...             ...     ...      ...
2024-12-24   458600   88700  1023600
2024-12-26  1277300  140100  2167200
2024-12-27   743400  287200  1800100
2024-12-30  1532000  211300  1531400
2024-12-31   683300  327900  1327400

[753 rows x 2970 columns]

In [43]:
#TASK 4,5,6

def calculate_ratios(returns, benchmark_returns):
    # Task 5: Beta Calculation
    beta = np.cov(returns, benchmark_returns)[0,1] / np.var(benchmark_returns)

    # Task 6: Annual Volatility Calculation (Daily Standard Deviation * sqrt(252))
    annual_volatility = np.std(returns) * np.sqrt(252)

    return beta, annual_volatility

def build_screener_from_clean(clean_df, tickers_list, index='^GSPC', start="2022-01-01", end="2025-01-01"):
    df = clean_df['Close'].copy()

    # 2. Download ONLY the benchmark data (S&P 500) for the matching timeframe
    print(f"Fetching benchmark data for {index}...")
    benchmark_data = yf.download(index, start=start, end=end)['Close']

    # 3. Merge the benchmark into the flattened stock dataset
    df[index] = benchmark_data

    # Task 4: Daily Return for the Benchmark
    benchmark = df[index].pct_change().dropna()
    results = []

    for ticker in tickers_list:
        # Safety check to ensure the ticker actually exists in our clean_data
        if ticker in df.columns and ticker != index:
            # Task 4: Daily Return for the Stock
            ret = df[ticker].pct_change().dropna()

            # Align dates so stock and benchmark match perfectly (Inner Join)
            aligned = pd.concat([ret, benchmark], axis=1, join='inner').dropna()

            # Tasks 5 & 6: Calculate the metrics
            beta, annual_vol = calculate_ratios(aligned[ticker], aligned[index])

            results.append({
                'Ticker': ticker,
                'Beta': beta,
                'Annual Volatility': annual_vol
            })

    return pd.DataFrame(results)

# --- Execution ---
print("\nTasks 4, 5 & 6: Calculating metrics directly from clean_data...")

# Execute the function using your existing clean_data and tickers variables
final_metrics_df = build_screener_from_clean(clean_data, tickers)

print("Calculations Complete. Final Metrics Data Shape:", final_metrics_df.shape)
display(final_metrics_df.head())

[*********************100%***********************]  1 of 1 completed

Tasks 4, 5 & 6: Calculating metrics directly from clean_data...
Fetching benchmark data for ^GSPC...

Calculations Complete. Final Metrics Data Shape: (495, 3)

  Ticker      Beta  Annual Volatility
0    MMM  0.790522           0.296581
1    AOS  0.920267           0.278284
2    ABT  0.672282           0.218008
3   ABBV  0.297552           0.221606
4    ACN  1.095940           0.270146

In [44]:
# Check the first ticker's prices
first_ticker = clean_data['Close'].columns[0]
sample_price = clean_data['Close'][first_ticker].iloc[0]

# If there are more than 2 decimal places, it's adjusted!
if round(sample_price, 2) != sample_price:
    print(f"CONFIRMED: Your 'Close' column is already Adjusted Close (Value: {sample_price})")
else:
    print("Your 'Close' column appears to be raw prices.")

CONFIRMED: Your 'Close' column is already Adjusted Close (Value: 156.47999572753906)

In [ ]:
final_metrics_df

    Ticker      Beta  Annual Volatility
0      MMM  0.784780           0.295457
1      AOS  0.925682           0.278488
2      ABT  0.673212           0.217694
3     ABBV  0.299496           0.219811
4      ACN  1.095664           0.270152
..     ...       ...                ...
490    XYL  1.069123           0.272503
491    YUM  0.634253           0.191208
492   ZBRA  1.502187           0.399784
493    ZBH  0.737483           0.244994
494    ZTS  0.917831           0.274833

[495 rows x 3 columns]